### ISSUE TITLE
Level one accounts don't work 

### ISSUE THREAD

**Issue by koderian** [velotoxicsounds/Microsoft-Rewards-Bot#24]
Level one accounts don't work with all

**Comment by velotoxicsounds** [comment]
Hello

I am aware of the error and is also noted on the Github page. Unfortunately, I don't currently have any Level 1 accounts so I can't implement this. My family account usage is also completely exhausted ^^. 

I look at that again the days and try to find a solution.

Greetings

**Comment by velotoxicsounds** [comment]
The project will no longer be supported. Microsoft has found a new anti-bot measure and detected all my accounts. Closed
