### ISSUE TITLE
Only does first daily set. No searches, no punchcards, just first set

### ISSUE THREAD

**Issue by koderian** [velotoxicsounds/Microsoft-Rewards-Bot#25]
Running Ubuntu 20.04. Python is 3.8. Command I use is `python3.8 ms_rewards.py --headless --all`

Logs from /logs/ms_rewards.log: [https://paste.ubuntu.com/p/sbdkRv4CKT/](https://paste.ubuntu.com/p/sbdkRv4CKT/)
I removed my account name for anonymity

**Comment by koderian** [comment]
@velotoxicsounds

**Comment by velotoxicsounds** [comment]
The project will no longer be supported. Microsoft has found a new anti-bot measure and detected all my accounts. Closed
