### ISSUE TITLE
Bot Closed

### ISSUE THREAD

**Issue by velotoxicsounds** [velotoxicsounds/Microsoft-Rewards-Bot#26]
The development of my side is stopped. Microsoft has offered a new method to find and block accounts. Therefore, I will not proceed any further

**Comment by KaxonDev** [comment]
Phone verified accounts still work fine.

**Comment by koderian** [comment]
What did they offer?

**Comment by HQModz** [comment]
LOL nothing has changed, there's no new anti-bot measure. You messed up somewhere along the way and went too hard with too many accounts. Are there any other forks that have taken over development? Please let me know.

**Comment by hidingfromu** [comment]
anyone know one that works still?

**Comment by KaxonDev** [comment]
Use godmaster007's fork; it's still functional. Sad this guy gave up after hitting a small road bump.

**Comment by HQModz** [comment]
Anyoone know of a new working bot?
